### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by solcre** [ReadyTalk/cukefarm#14]
Hey your project rocks! I love it! We do everything very similar to your framework. 

The only problem is we can't get this to work.

This is our project structure

/test/e2e/features/ => Features inside
/test/e2e/pages/ => Page Objects inside
/test/e2e/steps/ => Custom steps
/test/e2e/support/ => PageObjectMap.coffee and World.coffee

/test/protractor.conf.coffee with contents:

```
config = require('cukefarm').config

config.specs = 'e2e/features/**/*.feature'
config.capabilities.browserName = 'chrome'
config.cucumberOpts.require = ['./e2e/support/World.coffee', './e2e/support/PageObjectMap.coffee', './e2e/steps/**/*.js']

exports.config = config
```

(Notice I didn't use coffee script syntax in the config.cucumberOpts.require because it didn't work, btw, I hate coffee script so much! I would love your documentation without coffee examples hehe)

/test/support/PageObjectMap.coffee with contents:
```
globule = require 'globule'
path = require 'path'

files = globule.find 'e2e/pages/**/*.coffee'
for file in files
  page = require path.resolve(file)
  module.exports[page.name] = page.class
```

/test/support/World.coffee with contents:

```
World = require('cukefarm').World

World::pageObjectMap = require('./PageObjectMap')

module.exports.World = World
```

When I run: grunt protractor I get:

5 steps (5 undefined)

You can implement step definitions for undefined steps with these snippets:

this.Given(/^I am on the "([^"]*)" page$/, function (arg1, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.When(/^I type "([^"]*)" in the "([^"]*)" field$/, function (arg1, arg2, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.When(/^I click the "([^"]*)" button$/, function (arg1, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.Then(/^I should be on the "([^"]*)" page$/, function (arg1, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.Then(/^the "([^"]*)" should contain the text "([^"]*)"$/, function (arg1, arg2, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

**Comment by thompsnm** [comment]
Hey @solcre , I'm so glad you're giving this a try! I think the issue is in your /test/protractor.conf.coffee file. You're assigning the config.cucumberOpts.require to your own array, but you should be concatenating the contents of your array onto the existing config.cucumberOpts.require array. This is because CukeFarm has already populated that array with the path to it's own General Step Defs, so overriding it will mean Cucumber.js won't be able to find definition for those steps. Try replacing this line in /test/protractor.conf.coffee:
```
config.cucumberOpts.require = ['./e2e/support/World.coffee', './e2e/support/PageObjectMap.coffee', './e2e/steps/**/*.js']
```
with this:
```
config.cucumberOpts.require = config.cucumberOpts.require.concat ['./e2e/support/World.coffee', './e2e/support/PageObjectMap.coffee', './e2e/steps/**/*.js']
```
I'm not sure why the CoffeeScript syntax didn't work for you without seeing the code you tried. In any case, let me know if you have any more issues getting set up. Everything else looks good, so I think that's the last piece of the puzzle!

**Comment by solcre** [comment]
I converted all to .js and now I'm getting a new error: 

TypeError: Cannot read property 'Search' of null
  at World.<anonymous> (/home/matias/WorkSpace/Projects/myproject/node_modules/cukefarm/lib/step_definitions/GeneralStepDefs.js:9:48)
  at process._tickDomainCallback (node.js:381:11)

**Comment by solcre** [comment]
fixed it!!!

My World.js was missing the .prototype when seting the pageObject. I didn't use a coffee script compiler for that small file and missed the .prototype. 

That's why I hate coffeescript! hehe

**Comment by thompsnm** [comment]
Glad to hear it! I'll add a ticket to convert the example code to JS. That probably makes the most sense given the rest of the documentation and the lib that npm installs are all in JS.

**Comment by solcre** [comment]
Cool!!! I would love to help with this framework, it looks great for us.
Can't code in coffeescript though :(



[image: Solcre Technology Solutions]

Matias Fuster Coll
Solcre Technology Solutions
www.solcre.com
+598 2706 9927
Ing. Luis P. Ponce 1443A
11602 Montevideo, Uruguay

**Comment by thompsnm** [comment]
Gotcha, thanks for the offer. Our team uses coffeescript for our development, so the src files will remain in that language. Definitely give us any feedback you have as you start using CukeFarm more and more though!

**Comment by solcre** [comment]
Ok cool!

This is my first feedback:

In this step definition:

this.Then(/^(?:the )?"([^"]*)" should (?:have|contain) the text
"([^"]*)"$/, function(el, text, callback) {

There is a problem if the text is not currently visible, for example I'm
trying to assert that a text from a dropdown menu exists. I used to have
this working with getInnerHtml instead of getText.

So a possible solution would be to have 2 definitions, one that match's:
... have the text "Foo" visible (uses getText()) and one that match's ...
have the text "Foo" (uses getInnerHtml()).

Or another option would be to leave it as it is and add: ... have the html
"blah"



[image: Solcre Technology Solutions]

Matias Fuster Coll
Solcre Technology Solutions
www.solcre.com
+598 2706 9927
Ing. Luis P. Ponce 1443A
11602 Montevideo, Uruguay

**Comment by watsoncj** [comment]
I ran into this issue last week and was surprised to learn that the getText API only returns visible text.

I'm more in favor of adding a step definition for:

`Then the "element" should contain the HTML "blah"`

This would be less likely to break existing tests.

In my case I ended up having to do a reality check and ask: "Do I really need a test that validates hidden text in the DOM?".

I'd ask @thompsnm if he feels that the step def is common enough to include in cukefarm.

**Comment by dansomething** [comment]
:+1: @watsoncj 

In most cases I would expect you want the test to fail if the text is not actually being displayed. This comes up quite often in JavaScript driven sites that rely on hiding and showing elements to control the state of the page.

**Comment by solcre** [comment]
As you said "in most cases". In my case I have a menu that gets collapsed
on resolutions smaller than 1440px. In that menu I have some texts like the
user logged in and his avatar that I want to assert. In this case I find
the use of getInnerHtml():

El martes, 19 de mayo de 2015, Dan Hansen <notifications@github.com>
escribió:

> [image: :+1:] @watsoncj <https://github.com/watsoncj>
>
> In most cases I would expect you want the test to fail if the text is not
> actually being displayed. This comes up quite often in JavaScript driven
> sites that rely on hiding and showing elements to control the state of the
> page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReadyTalk/cukefarm/issues/14#issuecomment-103710484>.
>


-- 


[image: Solcre Technology Solutions]

Matias Fuster Coll
Solcre Technology Solutions
www.solcre.com
+598 2706 9927
Ing. Luis P. Ponce 1443A
11602 Montevideo, Uruguay

**Comment by thompsnm** [comment]
I'd say that if you want to automate that verification using Cucumber/Protractor, you should add a step that expands the menu before doing your verification. If that seems like unnecessary cruft in your scenario, then I would reassess what verification you really need to be doing. Perhaps at the Cucumber level you could just verify what elements are or are not displayed after resizing, then supplement tests at a less verbose, faster, lower level (i.e. Mocha tests running in [Karma](http://karma-runner.github.io/0.12/index.html)) that verify the structure of the page.
