### ISSUE TITLE
CukeFarm doesnt work with cucumberjs 0.5

### ISSUE THREAD

**Issue by jmartine** [ReadyTalk/cukefarm#19]
I'm getting issues with running cukefarm with the latest version of cucumberjs.  Reading the change log show that the callback function was rewritten.   I'm assuming that this is the problem with the incompatibility.

**Comment by thompsnm** [comment]
I did some digging and our issues likely trace back to [this issue](https://github.com/cucumber/cucumber-js/issues/367) in Cucumber. CukeFarm's `Then` steps commonly use the [`notify()`](https://github.com/domenic/chai-as-promised#working-with-non-promisefriendly-test-runners) function provided chai-as-promised to call the Step Def's `callback()` function. Unfortunately, CoffeeScript implicitly returns the final line of any function, so as a result we end up returning a promise as well as calling the callback, which yields the behavior described in the linked issue.
