### ISSUE TITLE
Step defs that interact with elements should wait until they are displayed

### ISSUE THREAD

**Issue by thompsnm** [ReadyTalk/cukefarm#28]
If a step def needs to interact with an element, it should wait for the element to be displayed to prevent errors while the application changes state. For instance, the following step def

```
@When /^I click the "([^"]*)"(?: )?(link|button|drop down list|tab|)$/, (elementName, elementType) ->
  elementType = @transform.elementTypeToVariableName(elementType)
  element = @transform.stringToVariableName(elementName + elementType)
  @currentPage[element].click()
```

may be re-written as

```
@When /^I click the "([^"]*)"(?: )?(link|button|drop down list|tab|)$/, (elementName, elementType) ->
  elementType = @transform.elementTypeToVariableName(elementType)
  element = @transform.stringToVariableName(elementName + elementType)
  browser.wait @currentPage[element].isDisplayed
    .then => @currentPage[element].click()
```

Ensure that the wait only lasts as long as the `browser.manage().timeouts().implicitlyWait` setting.

**Comment by wyvern8** [comment]
@thompsnm i'd be very keen to see this implemented, as I'm seeing our testers use explicit waits to workaround this eg.  'I wait for 1 second'.   Should be fairly simple to add as above?
