### ISSUE TITLE
There is no way to capture double quotes inside of many capture groups

### ISSUE THREAD

**Issue by thompsnm** [ReadyTalk/cukefarm#29]
Many capture groups use the regex pattern `"([^"]*)"`, which prohibits capturing double quotes. This becomes an issue when you want to write a step like

```
Then the "Error Message" should contain the text "Please provide a name for this phone number, such as "My Mobile" or "Desk Phone.""
```

where the text you need to capture contains double quotes.

**Comment by watsoncj** [comment]
I found this example regex that handles escaped quotes.

http://stackoverflow.com/questions/481282/how-can-i-match-double-quoted-strings-with-escaped-double-quote-characters

**Comment by watsoncj** [comment]
Most languages don't support the form mentioned in the description because of the ambiguity in parsing. There are two common approaches.

Escaping:

    Then the "Error Message" should contain the text "Please provide a name for this phone number, such as \"My Mobile\" or \"Desk Phone.\""

Optional Single Quotes:

    Then the 'Error Message' should contain the text 'Please provide a name for this phone number, such as "My Mobile" or "Desk Phone."'

**Comment by thompsnm** [comment]
Thanks for the input @watsoncj ! Both are good options; of the two I would lean towards Optional Single Quotes (and perhaps even optional \` characters to support strings with mixed single and double quotes).

I've also been kicking around the idea of capturing _all_ characters between two double quote literals, by changing instances of the regex `"([^"]*)"`  to `"(.*)"`. This would mean all steps in the feature would consistently use double quotes for captures and not need the extra noise of escape characters in your documentation. The trouble there of course is that it would prevent us from writing more complex step definitions due to ambiguity issues. For instance, steps that matched the pattern:

    Then the "(.*)" should contain the text "(.*)" and the "(.*)" should contain the text "(.*)"

would also match:

    Then the "(.*)" should contain the text "(.*)"

so the two of them could not live in the same project. I've been trying to decide if that limitation is really all that harmful; I haven't come to a conclusion on that yet.

**Comment by thompsnm** [comment]
Looks like the pattern CukeFarm adopted has now been standardized in Cucumber v2 with their [`stringInDoubleQuotes` built in transform](https://github.com/cucumber/cucumber-js/blob/e8a785ae5eb9d401c37a8a1c9d8b653b3ec1cea9/docs/support_files/api_reference.md#addtransformcapturegroupregexps-typename-transformer). As such, CukeFarm v5 should be updated to use the `stringInDoubleQuotes` transform to adhere to Cucumber standards going forward and this ticket should be closed as "won't fix".
