### ISSUE TITLE
pulling current page into custom step definitions

### ISSUE THREAD

**Issue by mozillalives** [ReadyTalk/cukefarm#38]
I'm writing my own custom step definitions and I'm not sure how to pull in the current page object. How should I go about this?

**Comment by thompsnm** [comment]
All you have to do is provide your World constructor to Cucumber in your Step Def file by calling `this.World = require('path/to/your/world/file').World`. From there you can access any property of the World (which includes the current page object) from within your Step Defs simply using `this` thanks to a little magic that Cucumber does behind the scenes. For instance, if you need to call the `get()` function on the current page object within a particular Step Def and then do something, your Step Def file would look something like this:

    module.exports = function() {

      this.World = require('path/to/your/world/file').World

      this.Given /^I am logged into RTD$/, function(callback) {
        this.currentPage.get().then function() {
          // Do something
          callback();
        };
      };
    }

For more info on Step Definitions take a look at the [Cucumber.js docs](https://github.com/cucumber/cucumber-js/tree/7764eb73492efa6a2fe458164fcc50ce265f5180#step-definitions).

**Comment by mozillalives** [comment]
Thanks! I'll give this a try.
