### ISSUE TITLE
Upgrade dependencies for protractor 4

### ISSUE THREAD

**Issue by wyvern8** [ReadyTalk/cukefarm#39]
Hi,

It would be great if a new release could be packaged with deps updated:

protractor ^4.0.0
cucumber ^1.0.0
protractor-cucumber-framework ^0.6.0

Seems to work with these versions.

Thanks,
Andrew

**Comment by wyvern8** [comment]
fyi - this part of GeneralStepDefs may need to be updated:

supportCodeLibrary.registerHandler 'StepResult', (event, callback) ->
    currentStepResult = event.getPayloadItem 'stepResult'
    callback()

as there are warnings logged:

[ERROR] cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
[ERROR] getPayloadItem will be removed in the next major release

**Comment by thompsnm** [comment]
Thanks for the heads up! I'll try to publish a new release this week.

**Comment by thompsnm** [comment]
Got the PR up, see #41. Barring any issues I'll move forward with publishing a new version next week.

**Comment by wyvern8** [comment]
Great!  Will give it a test over the next day or two.

**Comment by wyvern8** [comment]
i have compiled and tested your updates locally and it looks good.  thanks

**Comment by thompsnm** [comment]
This has been published as [`4.0.0`](https://www.npmjs.com/package/cukefarm), sorry for the delay.
